apiVersion: v1
kind: Service
metadata:
  name: gradio-service
spec:
  selector:
    app: gradio
  ports:
    - protocol: TCP
      port: 80 # Внешний порт, через который будет доступно приложение
      targetPort: 8080 # Порт внутри подов
  type: LoadBalancer
